### PR TITLE
Trigger Support

### PR DESCRIPTION
**Pull request by alondahari**
https://github.com/lookback/meteor-tooltips/issues/6

### CODE REVIEW

**Comment by johanbrook** [comment]
Hi @jazzdragon! 

This works great! Can I ask of two things:
- Pull down latest `origin/master` and merge it in, please. I noticed your fork is some commits behind.
- What are your thoughts on event namespacing? I saw you went with event names like `showTooltip`, but I'd prefer namespacing like: `tooltips:show` etc. instead.

**Comment by alondahari** [comment]
Hey,
Sorry it took me a little while.
Ready to merge!

A suggestion: currently the way you set it up, tooltips are treated all as one and not separately, so if I click and show one and then hover over another for example, the first one will be affected. I can think of use cases where this will be unwanted behavior.

**Comment by johanbrook** [comment]
Thanks!

> A suggestion: currently the way you set it up, tooltips are treated all as one and not separately, so if I click and show one and then hover over another for example, the first one will be affected. I can think of use cases where this will be unwanted behavior.

Yep, there is only one, single "instance" of a tooltip right now. The reason is simply that I yet haven't run into a scenario where multiple instances would be better.

**Comment by johanbrook** [comment]
This is now published on Atmosphere as 0.5.0.

**Pull request merged**
